<?php

namespace Database\Seeders;

use App\Models\FaqKnowledgeBase;
use Illuminate\Database\Seeder;

/**
 * The chatbot's built-in answers. Runs on every deploy (start.sh), keyed on the
 * question text, so editing an answer here updates it in place.
 *
 * Matching without an AI key is by keyword overlap (ChatbotService::processQuery):
 * only words longer than 3 letters count, compared exactly — so keywords list
 * plural/verb forms and words distinctive to each answer. With a Gemini key, all
 * active entries are the AI's context.
 *
 * Answers mirror the live rules (clock-in window, interview windows, promissory
 * notes, claim stubs…). No peso amounts and no stipend frequency are stated on
 * purpose — the DSA announces those.
 */
class FaqSeeder extends Seeder
{
    /** Superseded questions: switched off (not deleted) so the live table stays clean. */
    private const RETIRED = [
        'How do I record my time-in and time-out?', // merged into "How do I clock in for attendance?"
    ];

    public function run(): void
    {
        $faqs = [
            // ── Accounts & signing in ─────────────────────────────────────────
            ['category' => 'account', 'question' => 'How do I create a SWAP Portal account?', 'answer' => 'Open the SWAP Portal and choose Register (it is available while the DSA has the application period open). Use your MSU-Main student email ending in @s.msumain.edu.ph, your 9-digit student ID, and a password of at least 8 characters with upper- and lower-case letters and a number. After registering, open the verification link sent to your email — you can sign in only after verifying.', 'keywords' => ['register', 'registration', 'signup', 'create', 'account', 'sign'], 'sort_order' => 1],
            ['category' => 'account', 'question' => 'Why can’t I register with my Gmail or personal email?', 'answer' => 'Registration only accepts your MSU-Main student email, the one ending in @s.msumain.edu.ph. Personal addresses (Gmail, Yahoo, etc.) and staff addresses are refused. If you do not have your student email yet, ask the university’s registrar or ICT office.', 'keywords' => ['gmail', 'yahoo', 'personal', 'institutional', 'student', 'email', 'domain'], 'sort_order' => 2],
            ['category' => 'account', 'question' => 'What student ID number should I use when registering?', 'answer' => 'Enter your student ID as exactly 9 digits, numbers only (for example 200912345). Each student ID can be registered only once — if it says the ID is already taken, you may already have an account; try signing in or resetting your password.', 'keywords' => ['student', 'number', 'digits', 'idnumber', 'taken'], 'sort_order' => 3],
            ['category' => 'account', 'question' => 'Why does it say the application period is closed?', 'answer' => 'The DSA opens and closes the application period each semester. While it is closed, new accounts and new applications cannot be submitted. Watch the SWAP Portal home page or DSA announcements for the next opening.', 'keywords' => ['closed', 'period', 'open', 'opening', 'started', 'available'], 'sort_order' => 4],
            ['category' => 'account', 'question' => 'I didn’t receive my verification email. What should I do?', 'answer' => 'Check your spam or junk folder first. On the sign-in page, use “Resend verification email” and enter your student email — wait a minute between tries. Once you open the link, your account is activated and you can sign in.', 'keywords' => ['verification', 'verify', 'resend', 'receive', 'received', 'spam', 'activate', 'activation'], 'sort_order' => 5],
            ['category' => 'account', 'question' => 'Why can’t I sign in?', 'answer' => 'Common reasons: the email or password is wrong (check for typos and Caps Lock); your email is not verified yet (open the verification link or resend it); your account was deactivated (contact the DSA Office); or there were too many attempts in a short time (wait a minute and try again). If you forgot your password, use “Forgot password”.', 'keywords' => ['login', 'signin', 'cannot', 'incorrect', 'credentials', 'wrong', 'blocked'], 'sort_order' => 6],
            ['category' => 'account', 'question' => 'I forgot my password. How do I reset it?', 'answer' => 'On the sign-in page choose “Forgot password”, enter your email, and open the reset link we send you. Set a new password with at least 8 characters, upper- and lower-case letters, and a number. The link expires after a while — request a new one if it no longer works.', 'keywords' => ['forgot', 'forgotten', 'reset', 'password', 'recover', 'link'], 'sort_order' => 7],
            ['category' => 'account', 'question' => 'Why was I signed out of the portal?', 'answer' => 'For security, each sign-in lasts up to 7 days. You are also signed out on your other devices when you change your password, and immediately if the DSA deactivates your account. Simply sign in again.', 'keywords' => ['signed', 'logged', 'logout', 'session', 'expired', 'again'], 'sort_order' => 8],
            ['category' => 'account', 'question' => 'My account says it has been deactivated. What now?', 'answer' => 'A deactivated account cannot sign in or use the portal. Only the DSA can reactivate it — email dsa@msumain.edu.ph or visit the DSA Office with your student ID.', 'keywords' => ['deactivated', 'disabled', 'inactive', 'suspended', 'reactivate'], 'sort_order' => 9],
            ['category' => 'account', 'question' => 'How do I update my profile or change my password?', 'answer' => 'Open the Profile page from the sidebar or your photo in the top bar. You can update your details and photo (JPG, PNG or WEBP up to 4 MB), save your digital signature, and change your password by entering your current password and a new one. Changing your password signs you out on your other devices.', 'keywords' => ['profile', 'password', 'update', 'account', 'change', 'photo', 'picture'], 'sort_order' => 10],
            ['category' => 'account', 'question' => 'How do supervisors and DSA staff get an account?', 'answer' => 'Staff accounts are created by invitation. A DSA admin sends an invitation email; open the link within 3 days, set your name and password, and your account is ready with the right role. If the link has expired, ask the DSA for a new invitation.', 'keywords' => ['staff', 'invitation', 'invite', 'invited', 'supervisor', 'account'], 'sort_order' => 11],

            // ── Eligibility ───────────────────────────────────────────────────
            ['category' => 'eligibility', 'question' => 'Who is eligible to apply for the SWAP program?', 'answer' => 'SWAP is for qualified MSU students who need financial support to stay in school. Priority goes to 3rd, 4th and 5th year college students carrying at least 15 units this semester (freshmen and sophomores may apply but get the least priority). Under BOR Res. No. 6, s. 1992, assistantships are academic — in instruction or research — and related to your field.', 'keywords' => ['eligible', 'eligibility', 'qualify', 'qualified', 'requirement', 'requirements', 'financial', 'units'], 'sort_order' => 12],
            ['category' => 'eligibility', 'question' => 'Can graduating students apply for SWAP?', 'answer' => 'Yes. Graduating students may apply, and may carry fewer than 15 units if it is their last load.', 'keywords' => ['graduate', 'graduating', 'senior', 'last', 'load'], 'sort_order' => 13],
            ['category' => 'eligibility', 'question' => 'Can first or second year students apply?', 'answer' => 'Yes, freshmen and sophomores are still eligible to apply, but they are given the least priority. 3rd, 4th and 5th year students come first.', 'keywords' => ['freshman', 'freshmen', 'sophomore', 'sophomores', 'first', 'second', 'year'], 'sort_order' => 14],
            ['category' => 'eligibility', 'question' => 'Can I apply every semester?', 'answer' => 'Yes, applications re-open every semester. You can have only one application in progress at a time and one application per academic year and semester. Current recipients use Renewal instead of a new application.', 'keywords' => ['every', 'semester', 'again', 'reapply', 'next'], 'sort_order' => 15],

            // ── Applying ──────────────────────────────────────────────────────
            ['category' => 'application', 'question' => 'What documents are required for the SWAP application?', 'answer' => 'Upload four documents with your application: your Certificate of Registration (COR), your Grade Card, a Letter of Intent, and a 2×2 photo. Each file can be PDF, JPG or PNG, up to 5 MB.', 'keywords' => ['document', 'documents', 'requirement', 'requirements', 'certificate', 'registration', 'grades', 'grade', 'letter', 'intent', 'photo'], 'sort_order' => 16],
            ['category' => 'application', 'question' => 'How do I submit my SWAP application?', 'answer' => 'Register and verify your account, then sign in and open Application. Choose the academic year and semester, upload your COR, Grade Card, Letter of Intent and 2×2 photo, and submit. You will be notified in the portal (and by email) at every step: review, interview, and decision. Portal: https://swap-project-nqqw.vercel.app/', 'keywords' => ['submit', 'apply', 'application', 'portal', 'online', 'steps', 'start'], 'sort_order' => 17],
            ['category' => 'application', 'question' => 'How long does the application review take?', 'answer' => 'The DSA reviews applications during and after the application period. Review time depends on the number of applicants, so there is no fixed number of days — you will get a notification (and email) as soon as your application moves to review, when an interview is scheduled, and when a decision is made.', 'keywords' => ['review', 'processing', 'waiting', 'decision', 'days', 'long', 'result'], 'sort_order' => 18],
            ['category' => 'application', 'question' => 'How do I check my application status?', 'answer' => 'Sign in and open your Dashboard or your application. It shows the current status — Submitted, Under review, Interview scheduled, Approved, or Rejected (with the DSA’s remarks) — plus your interview details. You also get a notification whenever the status changes.', 'keywords' => ['status', 'dashboard', 'check', 'application', 'progress', 'track'], 'sort_order' => 19],
            ['category' => 'application', 'question' => 'What do the application statuses mean?', 'answer' => 'Submitted: received, waiting for the DSA. Under review: the DSA is checking your documents. Interview scheduled: see the date, time and venue or meeting link. Approved: you passed and will be assigned to an office. Rejected: not accepted this time; the DSA’s remarks explain why.', 'keywords' => ['statuses', 'meaning', 'mean', 'submitted', 'approved', 'rejected', 'scheduled'], 'sort_order' => 20],
            ['category' => 'application', 'question' => 'Can I cancel or withdraw my application?', 'answer' => 'You can cancel your application only while it is still “Submitted”. Once the DSA starts reviewing it, it can no longer be cancelled from the portal — contact the DSA Office if you need to withdraw.', 'keywords' => ['cancel', 'withdraw', 'delete', 'remove', 'undo'], 'sort_order' => 21],
            ['category' => 'application', 'question' => 'Why can’t I submit another application?', 'answer' => 'You can have only one application in progress at a time, and one per academic year and semester. If your application was approved, wait for your office assignment instead of applying again.', 'keywords' => ['another', 'second', 'twice', 'again', 'duplicate', 'progress'], 'sort_order' => 22],
            ['category' => 'application', 'question' => 'My document upload failed. What should I do?', 'answer' => 'Make sure each file is a PDF, JPG or PNG and no larger than 5 MB, then try again. If the upload fails while submitting, the unfinished application is removed automatically so you can simply submit again.', 'keywords' => ['upload', 'uploading', 'failed', 'file', 'size', 'large', 'error'], 'sort_order' => 23],
            ['category' => 'application', 'question' => 'Where can I see the documents I uploaded?', 'answer' => 'Applicants can open the Documents page from the sidebar to view the files attached to their application.', 'keywords' => ['uploaded', 'documents', 'view', 'files', 'attached'], 'sort_order' => 24],

            // ── Interviews ────────────────────────────────────────────────────
            ['category' => 'interview', 'question' => 'What should I expect during the SWAP interview?', 'answer' => 'The interview is a short session with the DSA about your situation, your studies, and why you want to join SWAP. Be on time, and bring your ID and copies of the documents you submitted in case they are asked for.', 'keywords' => ['interview', 'prepare', 'expect', 'bring', 'ready'], 'sort_order' => 25],
            ['category' => 'interview', 'question' => 'When and where are interviews held?', 'answer' => 'Face-to-face interviews are held Monday to Friday between 7:00 AM and 5:00 PM, usually at the Office of the Dean of Student Affairs (DSA). Online interviews can be any day between 8:00 AM and 11:00 PM. Your notification and application page show your exact date, time and venue.', 'keywords' => ['interview', 'schedule', 'venue', 'where', 'time', 'face', 'office'], 'sort_order' => 26],
            ['category' => 'interview', 'question' => 'Where do I find the link for my online interview?', 'answer' => 'The meeting link is in your interview notification and on your application page under the interview details. Join a few minutes early from a device with a working camera and microphone.', 'keywords' => ['online', 'link', 'meeting', 'zoom', 'google', 'meet', 'virtual'], 'sort_order' => 27],
            ['category' => 'interview', 'question' => 'Can I reschedule my interview?', 'answer' => 'Only the DSA can move an interview. If you cannot attend, email dsa@msumain.edu.ph or visit the DSA Office as early as possible. When it is moved, you will get a new notification with the updated date and time.', 'keywords' => ['reschedule', 'change', 'interview', 'date', 'move', 'attend'], 'sort_order' => 28],
            ['category' => 'interview', 'question' => 'What happens if I miss my interview?', 'answer' => 'A missed interview is marked as a no-show, and your application cannot be approved until the interview is rescheduled and held. Contact the DSA Office right away to ask for a new schedule.', 'keywords' => ['missed', 'miss', 'noshow', 'absent', 'late'], 'sort_order' => 29],

            // ── After approval: office placement ─────────────────────────────
            ['category' => 'placement', 'question' => 'What happens after my application is approved?', 'answer' => 'The DSA assigns you to an office and a supervisor. You are notified with the office, its location and your supervisor, and your account becomes a SWAP recipient. Next: add your digital signature on your Profile, then report to your office and start clocking in.', 'keywords' => ['approved', 'after', 'next', 'assignment', 'assigned', 'placement'], 'sort_order' => 30],
            ['category' => 'placement', 'question' => 'Which office will I be assigned to?', 'answer' => 'The DSA decides your office based on its needs and your field of study, since assistantships are tied to your major. You can see your office and supervisor on your Dashboard once you are assigned.', 'keywords' => ['which', 'office', 'assigned', 'assignment', 'placed'], 'sort_order' => 31],
            ['category' => 'placement', 'question' => 'Can my office or supervisor change?', 'answer' => 'Yes, the DSA can move you to another office or supervisor during the semester. You will get a notification with your new office and supervisor, and the new office QR code applies from then on.', 'keywords' => ['transfer', 'reassigned', 'moved', 'change', 'office', 'supervisor', 'new'], 'sort_order' => 32],

            // ── Attendance: clocking in ───────────────────────────────────────
            ['category' => 'attendance', 'question' => 'How do I clock in for attendance?', 'answer' => 'Before you start: save your digital signature on your Profile and turn on your phone’s location. Then, at your office, Monday to Saturday between 6:00 AM and 5:30 PM: scan your office QR code with your phone camera, or open Scan QR, or paste the code on the Attendance page. Take the selfie if your office requires one, and you are clocked in. You must be on the office premises — the portal checks your GPS location.', 'keywords' => ['clock', 'clockin', 'timein', 'attendance', 'scan', 'record', 'start'], 'sort_order' => 33],
            ['category' => 'attendance', 'question' => 'What time can I clock in?', 'answer' => 'Clock-in is open Monday to Saturday, from 6:00 AM to 5:30 PM (Philippine time). It is closed on Sundays and outside those hours.', 'keywords' => ['time', 'hours', 'sunday', 'saturday', 'morning', 'late', 'window', 'open'], 'sort_order' => 34],
            ['category' => 'attendance', 'question' => 'Why won’t the system let me clock in?', 'answer' => 'The message on screen tells you why. Most common: you are outside the office premises (move closer and check your GPS); the QR code is from a different office; location access is off; you have no digital signature yet; a selfie is required; you are already clocked in; you already completed your required hours; it is Sunday or outside 6:00 AM–5:30 PM; you have no active assignment; or the office has no location set yet (tell the DSA).', 'keywords' => ['cannot', 'rejected', 'refused', 'error', 'clock', 'clockin', 'fail', 'failed', 'wont'], 'sort_order' => 35],
            ['category' => 'attendance', 'question' => 'Why is a signature needed before I can clock in?', 'answer' => 'Your saved signature is used to sign your stipend claim stub and your receipt, so the portal requires it before you render any duty. Open your Profile and draw or upload your signature once; the reminder disappears as soon as it is saved.', 'keywords' => ['signature', 'specimen', 'required', 'sign', 'draw', 'clock'], 'sort_order' => 36],
            ['category' => 'attendance', 'question' => 'Why do I have to take a selfie when clocking in?', 'answer' => 'The selfie is proof that you were at your office. It is required unless one of your office’s supervisors has turned it off. Allow camera access when asked; if the photo fails to save, your clock-in still goes through.', 'keywords' => ['selfie', 'photo', 'camera', 'picture', 'face'], 'sort_order' => 37],
            ['category' => 'attendance', 'question' => 'Why do I need to enable location, and what is geofencing?', 'answer' => 'Geofencing confirms you are physically at your assigned office when you clock in. The portal compares your phone’s GPS with the office location and its allowed radius (with some tolerance for a weak signal). This stops attendance from being recorded off-site, so keep location on and let the GPS settle before scanning.', 'keywords' => ['geofencing', 'geofence', 'location', 'enable', 'premises', 'radius'], 'sort_order' => 38],
            ['category' => 'attendance', 'question' => 'Why does it say my location is unverified?', 'answer' => 'Your attendance was recorded but flagged for your supervisor to double-check. This happens when the GPS fix was weak (accuracy worse than 100 m), when the exact same coordinates were reused from an earlier log, or when the distance from your last clock-in would need an impossible travel speed. Clock in on a phone with GPS on, ideally near a window or outdoors.', 'keywords' => ['unverified', 'location', 'accuracy', 'flagged', 'flag', 'weak', 'signal'], 'sort_order' => 39],
            ['category' => 'attendance', 'question' => 'It says I am already clocked in. What should I do?', 'answer' => 'You still have an open session — clock out first (submit your narrative, then scan your office QR). If the session is from an earlier day, it closes automatically after 12 hours; after that you can clock in again.', 'keywords' => ['already', 'clocked', 'open', 'session', 'twice'], 'sort_order' => 40],
            ['category' => 'attendance', 'question' => 'Can I clock in after completing my required hours?', 'answer' => 'No. Once your verified hours reach your required hours for the semester, clock-in stops — your service for the term is complete.', 'keywords' => ['completed', 'complete', 'finished', 'done', 'required', 'enough'], 'sort_order' => 41],
            ['category' => 'attendance', 'question' => 'What are the ways to scan my office QR code?', 'answer' => 'Three ways, all equivalent: point your phone camera at the office QR (it opens the portal and clocks you in), open Scan QR in the sidebar, or copy the QR code text and paste it on the Attendance page. The QR code is displayed at your office — ask your supervisor if you cannot find it.', 'keywords' => ['scan', 'scanner', 'camera', 'paste', 'code', 'qrcode', 'ways'], 'sort_order' => 42],

            // ── Attendance: clocking out ──────────────────────────────────────
            ['category' => 'clock_out', 'question' => 'How do I clock out?', 'answer' => 'On the Attendance page tap Clock Out. First fill in your narrative report (what you worked on — at least 10 characters for the summary and the activities), then scan your own office QR code. Your session then goes to your supervisor for verification.', 'keywords' => ['clockout', 'timeout', 'leave', 'leaving', 'finish', 'end', 'out'], 'sort_order' => 43],
            ['category' => 'clock_out', 'question' => 'What is a narrative report?', 'answer' => 'A narrative report is a short summary of a work session: what you did, the activities you completed, and any challenges. It is required before a normal clock-out (one per session), and your supervisor reads it when verifying your hours.', 'keywords' => ['narrative', 'report', 'summary', 'activities', 'tasks'], 'sort_order' => 44],
            ['category' => 'clock_out', 'question' => 'What happens if I forget to clock out?', 'answer' => 'If your office uses geofencing and you leave the premises for about 10 minutes while clocked in, you are clocked out automatically (no narrative needed). Any session left open longer than 12 hours is closed automatically and credited at most 12 hours. Still, always clock out properly so your hours are accurate.', 'keywords' => ['forget', 'forgot', 'forgotten', 'clockout', 'automatic', 'stale'], 'sort_order' => 45],
            ['category' => 'clock_out', 'question' => 'Why was I automatically clocked out?', 'answer' => 'The Attendance page noticed you were outside your office premises for about 10 minutes, and the server confirmed your location was outside the office area. Your hours up to that point were saved for verification. If you think it was a GPS error, tell your supervisor.', 'keywords' => ['automatically', 'auto', 'clocked', 'outside', 'kicked'], 'sort_order' => 46],
            ['category' => 'clock_out', 'question' => 'Can I clock out using another office’s QR code?', 'answer' => 'No. You must clock out with the QR code of your own assigned office. A code from another office is refused.', 'keywords' => ['another', 'different', 'office', 'wrong', 'code'], 'sort_order' => 47],

            // ── Hours & verification ──────────────────────────────────────────
            ['category' => 'hours', 'question' => 'How many service hours are required per semester?', 'answer' => 'The usual requirement is 200 hours per semester in your assigned office. Your exact number is set on your assignment and shown on your Hours page and Dashboard; your supervisor can adjust it.', 'keywords' => ['hours', 'service', 'requirement', 'semester', 'many', 'required', 'render'], 'sort_order' => 48],
            ['category' => 'hours', 'question' => 'How do I see my rendered hours and progress?', 'answer' => 'Open the Hours page to see your verified, pending and remaining hours, with a progress bar toward your requirement. For printable records, use the Duty Slip page (weekly slip or semester service report).', 'keywords' => ['rendered', 'progress', 'remaining', 'track', 'total', 'hours'], 'sort_order' => 49],
            ['category' => 'hours', 'question' => 'How does my supervisor verify my hours?', 'answer' => 'After you clock out, the session goes to your office supervisor as pending. They check your time and narrative report, then verify it or reject it with feedback. Only verified hours count toward your requirement and your stipend.', 'keywords' => ['verify', 'verification', 'verified', 'supervisor', 'approve', 'pending'], 'sort_order' => 50],
            ['category' => 'hours', 'question' => 'Why are some of my hours still pending?', 'answer' => 'Pending hours are sessions waiting for your supervisor to verify them. They appear on your Hours page but do not count toward your requirement until verified. If they stay pending for long, remind your supervisor.', 'keywords' => ['pending', 'waiting', 'unverified', 'counted', 'still'], 'sort_order' => 51],
            ['category' => 'hours', 'question' => 'What happens if my supervisor rejects my attendance log?', 'answer' => 'You receive a notification with your supervisor’s feedback. Rejected hours do not count toward your required hours or appear on your duty slip. Talk to your supervisor if you think it was a mistake.', 'keywords' => ['reject', 'rejected', 'supervisor', 'feedback', 'invalid', 'declined'], 'sort_order' => 52],
            ['category' => 'hours', 'question' => 'What are bonus hours?', 'answer' => 'Bonus hours are extra hours credited for approved work outside a normal clock-in, such as an event. Hours added by your supervisor count right away; hours added by the DSA need your supervisor’s approval first. They appear in the BONUS column of your duty slip and are included in your total.', 'keywords' => ['bonus', 'extra', 'manual', 'added', 'event'], 'sort_order' => 53],
            ['category' => 'hours', 'question' => 'Can my required hours change during the semester?', 'answer' => 'Yes. Your supervisor can adjust your required hours. If the DSA requests a change, your supervisor approves or rejects it first. Your Hours page always shows the current number.', 'keywords' => ['change', 'adjust', 'required', 'increase', 'decrease', 'hours'], 'sort_order' => 54],

            // ── Duty slips ────────────────────────────────────────────────────
            ['category' => 'duty_slip', 'question' => 'How do I print my duty slip?', 'answer' => 'Open Duty Slip in the sidebar, choose Weekly (pick the week) or Semester, and press Print. Both print on A4 portrait. The weekly slip shows your AM/PM times, BONUS hours and TOTAL per day; the semester service report summarises the whole term week by week.', 'keywords' => ['duty', 'slip', 'print', 'printing', 'weekly', 'download', 'semestral'], 'sort_order' => 55],
            ['category' => 'duty_slip', 'question' => 'Why are the signatures missing from my duty slip?', 'answer' => 'Your supervisor’s and your signature appear only when every day on that slip has been verified and both of you have saved a digital signature. Ask your supervisor to verify any pending days, and make sure your own signature is saved on your Profile.', 'keywords' => ['signatures', 'signature', 'missing', 'blank', 'duty', 'slip', 'unsigned'], 'sort_order' => 56],
            ['category' => 'duty_slip', 'question' => 'What is the control number on my duty slip?', 'answer' => 'Every duty slip has a Control No. The DSA can type it into the portal to confirm the slip is genuine and compare the printed total with the hours on record — so an altered slip is detected. Do not edit a printed slip by hand.', 'keywords' => ['control', 'number', 'authentic', 'genuine', 'fake', 'duty', 'slip'], 'sort_order' => 57],

            // ── Digital signature ─────────────────────────────────────────────
            ['category' => 'signature', 'question' => 'How do I add my digital signature?', 'answer' => 'Open your Profile and go to Digital Signature. Draw it on screen or upload an image (JPG, PNG or WEBP up to 2 MB), then save. You can replace or remove it anytime. Recipients need it to clock in; supervisors and the DSA use it on claim stubs and duty slips.', 'keywords' => ['signature', 'specimen', 'draw', 'upload', 'sign', 'digital', 'save'], 'sort_order' => 58],
            ['category' => 'signature', 'question' => 'If I change my signature, will my old claim stubs change?', 'answer' => 'No. Each claim stub keeps a copy of the signatures used when it was signed, so replacing your signature later only affects new stubs.', 'keywords' => ['change', 'replace', 'signature', 'old', 'stubs', 'previous'], 'sort_order' => 59],
            ['category' => 'signature', 'question' => 'Who can see my signature?', 'answer' => 'Only you, the DSA admins, and the supervisors who oversee you. A recipient can also see their own supervisor’s signature because it prints on their duty slip.', 'keywords' => ['signature', 'privacy', 'view', 'access', 'secure'], 'sort_order' => 60],
            ['category' => 'signature', 'question' => 'Why do I keep getting reminders to add a signature?', 'answer' => 'Recipients without a saved signature get a weekly reminder, and a banner on their pages, because clock-in needs one. Save your signature on your Profile and the reminders stop.', 'keywords' => ['reminder', 'reminders', 'banner', 'signature', 'nudge'], 'sort_order' => 61],

            // ── Stipend & claim stubs ─────────────────────────────────────────
            ['category' => 'stipend', 'question' => 'How much is the SWAP stipend?', 'answer' => 'The amount is set by the DSA based on the approved budget and is announced by the DSA Office. When your stipend is released, the exact amount is printed on your claim stub.', 'keywords' => ['stipend', 'allowance', 'amount', 'money', 'much', 'salary'], 'sort_order' => 62],
            ['category' => 'stipend', 'question' => 'When is the stipend released?', 'answer' => 'Your stipend is released after your required service hours are verified by your supervisor (or after an approved promissory note, if you fell short). The DSA then issues your claim stub and you are notified right away.', 'keywords' => ['release', 'released', 'when', 'payment', 'receive', 'stipend', 'schedule'], 'sort_order' => 63],
            ['category' => 'stipend', 'question' => 'How do I claim my stipend?', 'answer' => 'When you are notified that your stipend is ready: open Stipend, download your claim stub (PDF), and bring it to the University Banking Office. After you receive the money, tap Confirm receipt on the Stipend page and enter the name of the releasing officer or cashier. That completes your receiving slip.', 'keywords' => ['claim', 'claiming', 'collect', 'banking', 'cashier', 'receipt', 'stipend'], 'sort_order' => 64],
            ['category' => 'stipend', 'question' => 'What is a claim stub?', 'answer' => 'A claim stub is the official slip for your stipend. It has a control number (SWAP-STP-…), the amount and period, and the signatures of your supervisor and the DSA. You download it from the Stipend page and present it at the Banking Office.', 'keywords' => ['claim', 'stub', 'slip', 'control', 'number'], 'sort_order' => 65],
            ['category' => 'stipend', 'question' => 'Why can’t I download my claim stub?', 'answer' => 'Sometimes the stub cannot be generated for a moment. Wait a few minutes and try again. If it keeps failing, contact the DSA Office — your stipend record is safe either way.', 'keywords' => ['download', 'downloading', 'stub', 'generate', 'error', 'failed', 'claim'], 'sort_order' => 66],
            ['category' => 'stipend', 'question' => 'Why am I not eligible for a stipend yet?', 'answer' => 'A stipend is released only when your verified hours meet your requirement (or you have an approved promissory note). Pending or rejected hours do not count. You also cannot get a second stipend for a semester that already has one.', 'keywords' => ['eligible', 'eligibility', 'stipend', 'qualified', 'listed', 'released'], 'sort_order' => 67],
            ['category' => 'stipend', 'question' => 'Can I receive two stipends for the same semester?', 'answer' => 'No. There is one stipend per recipient per semester. If a claim stub was voided by the DSA before it was claimed, a new one can be issued for that semester.', 'keywords' => ['two', 'twice', 'double', 'second', 'same', 'semester'], 'sort_order' => 68],
            ['category' => 'stipend', 'question' => 'My claim stub was voided. What does that mean?', 'answer' => 'The DSA cancelled that stub before it was claimed, for example to correct an error. A voided stub cannot be used at the Banking Office. The DSA can issue a new one for the same semester — contact the DSA Office if you were not told why.', 'keywords' => ['voided', 'cancelled', 'invalid', 'stub'], 'sort_order' => 69],
            ['category' => 'stipend', 'question' => 'Where can I see my past stipends?', 'answer' => 'Open the Stipend page. It lists all your claim stubs with their status: ready to claim, claimed (with the date), or voided.', 'keywords' => ['past', 'history', 'previous', 'stipends', 'list', 'record'], 'sort_order' => 70],

            // ── Promissory notes ──────────────────────────────────────────────
            ['category' => 'promissory', 'question' => 'What is a promissory note?', 'answer' => 'If the semester has ended and you are still short on verified hours, you can submit a promissory note promising to make up the missing hours. If your supervisor approves it, the DSA can release your stipend, and you must finish the missing hours by the makeup deadline.', 'keywords' => ['promissory', 'note', 'short', 'lacking', 'promise', 'makeup'], 'sort_order' => 71],
            ['category' => 'promissory', 'question' => 'How and when do I submit a promissory note?', 'answer' => 'From the Stipend page, after the semester end date has passed and only if your verified hours are below your requirement. Attach your signed note (PDF, JPG or PNG up to 5 MB) and a short reason. Only one note can be pending at a time.', 'keywords' => ['promissory', 'submit', 'file', 'when', 'how', 'note'], 'sort_order' => 72],
            ['category' => 'promissory', 'question' => 'Who reviews my promissory note?', 'answer' => 'A supervisor who oversees your assignment (your assigned supervisor or a supervisor of your office). They approve it — recording how many hours you lack and setting a makeup deadline 7 days after the semester end — or reject it with remarks. You are notified either way.', 'keywords' => ['promissory', 'review', 'reviews', 'approve', 'approved', 'deadline'], 'sort_order' => 73],
            ['category' => 'promissory', 'question' => 'Why can’t I submit a promissory note?', 'answer' => 'The screen explains why. Usually: the semester has not ended yet; your verified hours already meet the requirement (no note needed); you already have a pending note; or the semester end date has not been set (ask the DSA).', 'keywords' => ['promissory', 'cannot', 'refused', 'note', 'submit'], 'sort_order' => 74],

            // ── Renewal ───────────────────────────────────────────────────────
            ['category' => 'renewal', 'question' => 'How do I renew my SWAP slot for next semester?', 'answer' => 'When the DSA opens the renewal window, go to Renewal in the sidebar and upload your updated Certificate of Registration (COR). No new interview is needed. Once approved, you continue in the same office with the same supervisor, and your hours start fresh for the new term.', 'keywords' => ['renew', 'renewal', 'continue', 'next', 'term', 'again'], 'sort_order' => 75],
            ['category' => 'renewal', 'question' => 'Why is the renewal closed?', 'answer' => 'The DSA opens renewal only for a set term. If it says renewal is not open yet or not fully configured, wait for the DSA announcement. Renewal is only for recipients who already had an assignment.', 'keywords' => ['renewal', 'closed', 'open', 'configured', 'unavailable'], 'sort_order' => 76],

            // ── Notifications ─────────────────────────────────────────────────
            ['category' => 'notifications', 'question' => 'What notifications will I receive?', 'answer' => 'You are notified about your application steps, interview schedules, approval or rejection, your office assignment, verified or rejected hours, promissory note decisions, and your stipend (ready to claim and received). Open the bell icon to read them; you can mark one or all as read. Many are also emailed.', 'keywords' => ['notification', 'notifications', 'bell', 'alert', 'alerts', 'email'], 'sort_order' => 77],
            ['category' => 'notifications', 'question' => 'Why don’t new notifications show up right away?', 'answer' => 'The bell updates when the page reloads or you navigate. If you are waiting for news, refresh the page.', 'keywords' => ['notifications', 'show', 'appear', 'refresh', 'late', 'realtime'], 'sort_order' => 78],

            // ── For supervisors ───────────────────────────────────────────────
            ['category' => 'supervisor', 'question' => 'How do I verify my students’ hours as a supervisor?', 'answer' => 'Open Verify. The Pending tab lists sessions waiting for you; check the time, narrative report and selfie, then Verify or Reject. Rejecting requires feedback, which the student sees. The Reviewed tab shows what you and your co-supervisors already decided.', 'keywords' => ['supervisor', 'verify', 'verifying', 'students', 'approve', 'reject'], 'sort_order' => 79],
            ['category' => 'supervisor', 'question' => 'Can I verify many attendance logs at once?', 'answer' => 'Yes. In Verify, select several pending logs and use Verify selected. Logs flagged for location issues are skipped and must be reviewed one by one.', 'keywords' => ['bulk', 'many', 'multiple', 'selected', 'once', 'batch'], 'sort_order' => 80],
            ['category' => 'supervisor', 'question' => 'What does a flagged attendance log mean?', 'answer' => 'The student’s location looked unreliable — weak GPS, coordinates reused from another log, or an impossible travel speed. The session is still recorded; check the narrative and selfie before verifying, and ask the student if something looks wrong.', 'keywords' => ['flagged', 'flag', 'suspicious', 'location', 'review'], 'sort_order' => 81],
            ['category' => 'supervisor', 'question' => 'Which students can I see and verify?', 'answer' => 'The students assigned to you, plus every student hosted by your office — supervisors of the same office share them. You cannot verify students of other offices.', 'keywords' => ['which', 'students', 'office', 'cosupervisor', 'shared', 'roster'], 'sort_order' => 82],
            ['category' => 'supervisor', 'question' => 'How do I see which students are clocked in right now?', 'answer' => 'Your Dashboard shows who is currently clocked in, with a live timer. Sessions open for more than 12 hours are left out because they are closed automatically.', 'keywords' => ['clocked', 'right', 'currently', 'live', 'present', 'duty'], 'sort_order' => 83],
            ['category' => 'supervisor', 'question' => 'How do I give a student bonus hours?', 'answer' => 'Open Students, choose the student, and add bonus hours with the date and a reason (from 0.25 to 24 hours, not a future date). Hours you add are verified immediately.', 'keywords' => ['bonus', 'give', 'grant', 'extra', 'manual', 'hours'], 'sort_order' => 84],
            ['category' => 'supervisor', 'question' => 'How do I change a student’s required hours?', 'answer' => 'Open Students, choose the student and edit Required hours. When the DSA requests a change, it appears there for you to approve or reject.', 'keywords' => ['required', 'change', 'adjust', 'student', 'request'], 'sort_order' => 85],
            ['category' => 'supervisor', 'question' => 'How do I turn the clock-in selfie on or off?', 'answer' => 'Open Office QR and use the clock-in selfie setting. When any supervisor of an office turns it off, the students they oversee can clock in without a selfie.', 'keywords' => ['selfie', 'turn', 'disable', 'enable', 'setting', 'camera'], 'sort_order' => 86],
            ['category' => 'supervisor', 'question' => 'Where is my office’s QR code?', 'answer' => 'Open Office QR in the sidebar. Print it or display it at your office so students can scan it to clock in and out.', 'keywords' => ['office', 'code', 'qrcode', 'print', 'display', 'where'], 'sort_order' => 87],
            ['category' => 'supervisor', 'question' => 'How do I review promissory notes as a supervisor?', 'answer' => 'Open Promissory in the sidebar. For each pending note, read the reason and attachment, then approve it (enter the lacking hours) or reject it with remarks.', 'keywords' => ['review', 'promissory', 'notes', 'supervisor', 'pending'], 'sort_order' => 88],
            ['category' => 'supervisor', 'question' => 'How do I export my students’ hours summary?', 'answer' => 'Open Summary in the sidebar to see each student’s required, verified, pending and remaining hours and whether they are on pace, then use Export to download a CSV for the DSA.', 'keywords' => ['export', 'summary', 'roster', 'download', 'report', 'excel'], 'sort_order' => 89],

            // ── For DSA admins ────────────────────────────────────────────────
            ['category' => 'admin', 'question' => 'How do I process applications as an admin?', 'answer' => 'Open Applications. Move a new application to review, schedule the interview, then approve or reject. A new application can be approved only after its interview was held (not a no-show); renewals skip the interview. Once approved or rejected, the decision is final.', 'keywords' => ['admin', 'process', 'applications', 'approve', 'decision', 'review'], 'sort_order' => 90],
            ['category' => 'admin', 'question' => 'How do I schedule or reschedule an interview?', 'answer' => 'From the application, choose the date, time and mode. Face-to-face: Monday to Friday, 7:00 AM–5:00 PM. Online: any day, 8:00 AM–11:00 PM, and a meeting link (https://…) is required. Use Reschedule to move it; the applicant is notified each time.', 'keywords' => ['schedule', 'scheduling', 'interview', 'reschedule', 'admin', 'slot'], 'sort_order' => 91],
            ['category' => 'admin', 'question' => 'How do I assign an approved applicant to an office?', 'answer' => 'Open Assignments, pick the approved applicant, then choose the office, supervisor, required hours (1–500) and start date. A student can have only one active assignment per term. The student is notified and becomes a recipient.', 'keywords' => ['assign', 'assignment', 'office', 'place', 'placement', 'admin'], 'sort_order' => 92],
            ['category' => 'admin', 'question' => 'How do I open or close applications and renewals?', 'answer' => 'On the Applications page, use the application-period switch (with an optional closed message) and the renewal switch, where you also set the renewal year and semester.', 'keywords' => ['open', 'close', 'period', 'renewal', 'toggle', 'switch'], 'sort_order' => 93],
            ['category' => 'admin', 'question' => 'How do I invite a supervisor or another admin?', 'answer' => 'Open Users and send an invitation with their email and role. They receive a link valid for 3 days to set up their account. Staff accounts are created only through invitations.', 'keywords' => ['invite', 'invitation', 'staff', 'supervisor', 'users', 'admin'], 'sort_order' => 94],
            ['category' => 'admin', 'question' => 'How do I deactivate a user?', 'answer' => 'Open Users and switch the account to inactive. The person is signed out immediately and cannot sign in until reactivated. Admin accounts cannot be deactivated or deleted, and you cannot delete your own account.', 'keywords' => ['deactivate', 'disable', 'user', 'remove', 'delete', 'block'], 'sort_order' => 95],
            ['category' => 'admin', 'question' => 'How do I release stipends?', 'answer' => 'Open Stipend and unlock it with your password (it stays unlocked for about 15 minutes of activity). Tick the eligible recipients and release — up to 100 at once. Each gets a signed claim stub and a notification. Your position title must be set on your Profile first.', 'keywords' => ['release', 'releasing', 'stipends', 'unlock', 'admin', 'eligible'], 'sort_order' => 96],
            ['category' => 'admin', 'question' => 'Why can’t I release a stipend?', 'answer' => 'Check that your position title is set on your Profile, that the recipient appears in the eligible list (verified hours met, or an approved promissory note), and that they do not already have a stub for that semester. After several wrong password attempts, wait a minute before trying again.', 'keywords' => ['cannot', 'release', 'title', 'position', 'blocked', 'stipend'], 'sort_order' => 97],
            ['category' => 'admin', 'question' => 'How do I void a claim stub?', 'answer' => 'On the Stipend page, choose the stub and Void it with a reason (your password or the unlock is required). Only stubs that have not been claimed can be voided. The recipient becomes eligible again for that semester.', 'keywords' => ['void', 'voiding', 'cancel', 'stub', 'mistake', 'admin'], 'sort_order' => 98],
            ['category' => 'admin', 'question' => 'How do I check if a duty slip is genuine?', 'answer' => 'Open Verify Slip and paste the Control No. printed on the slip. The portal tells you whether it is authentic and shows the hours on record for that period — compare it with the printed total.', 'keywords' => ['genuine', 'authentic', 'duty', 'slip', 'control', 'check', 'fake'], 'sort_order' => 99],
            ['category' => 'admin', 'question' => 'Where do I find reports, analytics and audit logs?', 'answer' => 'Reports lets you preview and download CSV reports (applications, recipients, stipend disbursement, offices) for a period. Analytics shows the dashboard figures, including claimed and awaiting-claim stipends. Audit Logs records who changed what and when.', 'keywords' => ['reports', 'analytics', 'audit', 'logs', 'export', 'statistics'], 'sort_order' => 100],
            ['category' => 'admin', 'question' => 'How do I set up an office and its geofence?', 'answer' => 'Open Offices to add or edit an office: name, head, location on the map, allowed radius, capacity and logo, and the supervisors assigned to it. Students of an office without a location cannot clock in until it is set.', 'keywords' => ['office', 'offices', 'setup', 'geofence', 'radius', 'location', 'map'], 'sort_order' => 101],

            // ── Privacy ───────────────────────────────────────────────────────
            ['category' => 'privacy', 'question' => 'Who can see my documents and photos?', 'answer' => 'Only you, the supervisors who oversee you, and the DSA admins. Links to your files do not work for other students.', 'keywords' => ['privacy', 'private', 'documents', 'photos', 'see', 'access'], 'sort_order' => 102],
            ['category' => 'privacy', 'question' => 'Is my location tracked all the time?', 'answer' => 'No. Your location is checked when you clock in and out, and while you are clocked in with the Attendance page open (to notice if you leave the premises). It is not tracked at any other time.', 'keywords' => ['tracked', 'tracking', 'location', 'privacy', 'always', 'monitor'], 'sort_order' => 103],

            // ── About the portal ──────────────────────────────────────────────
            ['category' => 'system', 'question' => 'How does the SWAP Portal system work?', 'answer' => 'The SWAP Portal runs the whole assistantship online: you register and apply with your documents, the DSA reviews and interviews you, and once approved you are assigned to an office. You clock in and out with your office QR code (location-checked), submit a narrative report each session, and your supervisor verifies your hours. When your hours are verified, the DSA releases your stipend as a claim stub you collect at the Banking Office.', 'keywords' => ['system', 'works', 'portal', 'overview', 'about', 'process'], 'sort_order' => 104],
            ['category' => 'system', 'question' => 'What are the roles in the SWAP Portal?', 'answer' => 'There are four roles: Applicants apply to the program; Recipients are approved students who render service hours; Supervisors verify the hours of students in their office; and Admins (DSA) manage applications, interviews, assignments, offices, and stipends.', 'keywords' => ['roles', 'applicant', 'recipient', 'supervisor', 'admin'], 'sort_order' => 105],
            ['category' => 'system', 'question' => 'How do I contact the DSA Office?', 'answer' => 'Email the Division of Student Affairs at dsa@msumain.edu.ph, or visit the DSA Office during working hours, Monday to Friday, 8:00 AM–5:00 PM.', 'keywords' => ['contact', 'email', 'office', 'reach', 'help', 'support'], 'sort_order' => 106],
            ['category' => 'system', 'question' => 'What device should I use for the SWAP Portal?', 'answer' => 'Any modern browser works for applying and reading. For attendance, use a phone with GPS and a camera so you can scan the QR code, share your location and take the selfie.', 'keywords' => ['device', 'phone', 'laptop', 'browser', 'mobile', 'computer'], 'sort_order' => 107],
            ['category' => 'system', 'question' => 'Who are the legendary minds behind the SWAP Portal?', 'answer' => 'According to my database, this portal was forged by the mythical duo: Jumailah A. Mamalampac and Norhadi M. Norodin. My AI algorithms ran a deep analysis on them and found that Jumailah possesses a brain power that breaks my CPU, while Norhadi is a 23-year-old entity whose level of "super pogi" violates the laws of physics. If this website crashes, it is not a bug—it is just the servers melting from their combined genius and Norhadi’s blinding good looks.', 'keywords' => ['developer', 'jumailah', 'norhadi', 'haddy', 'pogi', 'creator', 'built', 'genius'], 'sort_order' => 108],
        ];

        foreach ($faqs as $faq) {
            FaqKnowledgeBase::updateOrCreate(
                ['question' => $faq['question']],
                array_merge($faq, ['is_active' => true])
            );
        }

        FaqKnowledgeBase::whereIn('question', self::RETIRED)->update(['is_active' => false]);
    }
}
