<?php

namespace Database\Seeders;

use App\Models\FaqKnowledgeBase;
use Illuminate\Database\Seeder;

class FaqSeeder extends Seeder
{
    public function run(): void
    {
        $faqs = [
            ['category' => 'eligibility', 'question' => 'Who is eligible to apply for the SWAP program?', 'answer' => 'Students who are financially challenged, currently enrolled at MSU Marawi, with a GPA of at least 2.0, and in good academic standing are eligible to apply for the SWAP program.', 'keywords' => ['eligible', 'qualify', 'requirement', 'gpa', 'financial', 'enrolled'], 'sort_order' => 1],
            ['category' => 'eligibility', 'question' => 'Can graduating students apply for SWAP?', 'answer' => 'Yes, graduating students may apply for SWAP as long as they meet the eligibility requirements. However, priority is given to students with more remaining semesters.', 'keywords' => ['graduate', 'graduating', 'senior', 'last', 'year'], 'sort_order' => 2],
            ['category' => 'application', 'question' => 'What documents are required for the SWAP application?', 'answer' => 'Required documents include: Certificate of Enrollment, Certified True Copy of Grades, Certificate of Financial Need (from Barangay or Social Worker), 2x2 ID photo, and Recommendation Letter from a faculty member.', 'keywords' => ['document', 'requirement', 'requirement', 'certificate', 'grade', 'photo', 'recommendation'], 'sort_order' => 3],
            ['category' => 'application', 'question' => 'How do I submit my SWAP application?', 'answer' => 'You can submit your application through the SWAP Portal at swap.msu-marawi.edu.ph. Register an account, complete your profile, fill out the application form, and upload the required documents. The DSA Office will review your application and notify you of the outcome.', 'keywords' => ['submit', 'apply', 'application', 'portal', 'online', 'register'], 'sort_order' => 4],
            ['category' => 'application', 'question' => 'How long does the application review take?', 'answer' => 'The DSA Office typically reviews applications within 5-10 working days after the submission deadline. You will receive an email and in-app notification once a decision has been made.', 'keywords' => ['review', 'processing', 'waiting', 'decision', 'days', 'long'], 'sort_order' => 5],
            ['category' => 'service_hours', 'question' => 'How many service hours are required per semester?', 'answer' => 'Recipients are required to render 120 service hours per semester. Your supervisor will verify your rendered hours.', 'keywords' => ['hours', 'service', 'requirement', 'semester', 'many', 'required'], 'sort_order' => 6],
            ['category' => 'service_hours', 'question' => 'How do I record my time-in and time-out?', 'answer' => 'Use the QR code assigned to your office. Open the SWAP Portal, go to Attendance > Scan QR, and scan the code at your assigned office. Before timing out, you must submit a narrative report for that session.', 'keywords' => ['time', 'clock', 'qr', 'scan', 'attendance', 'record'], 'sort_order' => 7],
            ['category' => 'service_hours', 'question' => 'What happens if my supervisor rejects my attendance log?', 'answer' => 'If your supervisor rejects your log, you will receive a notification with their feedback. Rejected hours do not count toward your required 120 hours. Please contact your supervisor to discuss the rejection.', 'keywords' => ['reject', 'rejected', 'supervisor', 'feedback', 'invalid'], 'sort_order' => 8],
            ['category' => 'stipend', 'question' => 'How much is the SWAP stipend?', 'answer' => 'The SWAP stipend varies depending on the semester budget allocation. Typically, recipients receive between ₱2,000 to ₱5,000 per semester. The exact amount will be communicated upon approval of the semester budget.', 'keywords' => ['stipend', 'allowance', 'amount', 'money', 'pay', 'salary'], 'sort_order' => 9],
            ['category' => 'stipend', 'question' => 'When is the stipend released?', 'answer' => 'Stipends are released at the end of the semester, once all required service hours have been verified. You will receive a notification when your stipend is ready for release. Please coordinate with the DSA Office for the release schedule.', 'keywords' => ['release', 'when', 'payment', 'receive', 'stipend', 'schedule'], 'sort_order' => 10],
            ['category' => 'interview', 'question' => 'What should I expect during the SWAP interview?', 'answer' => 'The interview is a 15-30 minute session with a DSA staff member. You will be asked about your financial situation, academic performance, and motivation for joining SWAP. Please bring original copies of your submitted documents.', 'keywords' => ['interview', 'prepare', 'expect', 'question', 'bring', 'documents'], 'sort_order' => 11],
            ['category' => 'interview', 'question' => 'Can I reschedule my interview?', 'answer' => 'If you cannot attend your scheduled interview, please contact the DSA Office immediately at dsaoffice@msu-marawi.edu.ph or visit the office. Late rescheduling may result in application forfeiture.', 'keywords' => ['reschedule', 'change', 'interview', 'date', 'cancel'], 'sort_order' => 12],

            // ── How the SWAP Portal system works ──────────────────────────────
            ['category' => 'system', 'question' => 'How does the SWAP Portal system work?', 'answer' => 'The SWAP Portal manages the whole assistantship online: you apply and upload documents, the DSA reviews and interviews you, and once approved you render service hours at your assigned office. You clock in and out using your office QR code with GPS location verification, submit a short narrative report each session, and your supervisor verifies your hours. Your stipend is released once your required hours are verified.', 'keywords' => ['system', 'works', 'portal', 'overview', 'about', 'process'], 'sort_order' => 13],
            ['category' => 'system', 'question' => 'How do I clock in for attendance?', 'answer' => 'Go to the Attendance page, make sure your phone location is enabled, then scan or paste your assigned office QR code and tap Clock In. You must be physically on the office premises — the system checks your GPS location against the office geofence, so clock-ins from outside are rejected.', 'keywords' => ['clock', 'attendance', 'scan', 'geofence', 'premises', 'timein'], 'sort_order' => 14],
            ['category' => 'system', 'question' => 'How do I clock out?', 'answer' => 'On the Attendance page, tap Clock Out and scan your office QR code. A short narrative report will pop up asking what you worked on — fill it in and submit, and you will be clocked out automatically.', 'keywords' => ['clockout', 'timeout', 'leave', 'narrative', 'finish'], 'sort_order' => 15],
            ['category' => 'system', 'question' => 'Why do I need to enable location, and what is geofencing?', 'answer' => 'Geofencing confirms you are physically at your assigned office when you clock in or out. The system compares your phone GPS to the office location and a set radius. This prevents attendance from being recorded off-site, so your GPS must be enabled and reasonably accurate.', 'keywords' => ['geofencing', 'location', 'gps', 'enable', 'premises', 'why'], 'sort_order' => 16],
            ['category' => 'system', 'question' => 'What is a narrative report?', 'answer' => 'A narrative report is a short summary of what you did during a work session — the tasks you accomplished and any challenges. You submit it when you clock out, and your supervisor reads it when verifying your hours.', 'keywords' => ['narrative', 'report', 'summary', 'session', 'tasks'], 'sort_order' => 17],
            ['category' => 'system', 'question' => 'How do I see my rendered hours and progress?', 'answer' => 'Open the Hours page to see your verified, pending, and remaining hours toward your semester requirement, shown as a progress bar. The Reports section lets you view weekly, monthly, and semester breakdowns.', 'keywords' => ['hours', 'progress', 'rendered', 'remaining', 'track'], 'sort_order' => 18],
            ['category' => 'system', 'question' => 'How do I check my application status?', 'answer' => 'Log in and open your Dashboard. Your application status (submitted, under review, interview scheduled, approved, or rejected) is shown there, and you also receive a notification whenever it changes.', 'keywords' => ['status', 'dashboard', 'check', 'application', 'progress'], 'sort_order' => 19],
            ['category' => 'system', 'question' => 'What are the roles in the SWAP Portal?', 'answer' => 'There are four roles: Applicants apply to the program; Recipients are approved students who render service hours; Supervisors verify the hours of students in their office; and Admins (DSA) manage applications, interviews, assignments, offices, and stipends.', 'keywords' => ['roles', 'applicant', 'recipient', 'supervisor', 'admin'], 'sort_order' => 20],
            ['category' => 'system', 'question' => 'How does my supervisor verify my hours?', 'answer' => 'After you clock out, your log goes to your office supervisor as pending. They review your time and narrative report, then verify or reject it with feedback. Only verified hours count toward your requirement and stipend.', 'keywords' => ['verify', 'verification', 'supervisor', 'approve', 'pending'], 'sort_order' => 21],
            ['category' => 'system', 'question' => 'What happens if I forget to clock out?', 'answer' => 'If you leave the office geofence, the system automatically clocks you out after a short grace period. If a session is left open too long, the system also closes it automatically. Still, always try to clock out properly so your hours and narrative are accurate.', 'keywords' => ['forget', 'forgot', 'clockout', 'auto', 'open'], 'sort_order' => 22],
            ['category' => 'system', 'question' => 'How do I update my profile or change my password?', 'answer' => 'Open the Profile page from the sidebar or the avatar in the top bar. There you can update your information and change your password.', 'keywords' => ['profile', 'password', 'update', 'account', 'change'], 'sort_order' => 23],
            ['category' => 'system', 'question' => 'Why does it say my location is unverified?', 'answer' => 'A "Location unverified" note means your GPS fix was imprecise (low accuracy) when you clocked in or out — common indoors or on a laptop. Your attendance is still recorded but flagged for your supervisor to double-check. For best results, clock in on a phone with GPS enabled, outdoors if possible.', 'keywords' => ['unverified', 'location', 'accuracy', 'flagged', 'gps'], 'sort_order' => 24],
        ];

        foreach ($faqs as $faq) {
            FaqKnowledgeBase::updateOrCreate(
                ['question' => $faq['question']],
                array_merge($faq, ['is_active' => true])
            );
        }
    }
}
